- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 54000 # Floofstation - 15 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    min: 14400 # Floofstation - 4 hours

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 54000 # Floofstation - 15 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Medical dept time requirement
    department: Medical
    min: 14400 # Floofstation - 4 hours

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 54000 # Floofstation - 15 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    min: 14400 # Floofstation - 4 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    min: 14400 # Floofstation - 4 hours
  - !type:WhitelistRequirement # DeltaV - Whitelist requirement
